apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - ../istio/gateway.yaml
  - application-blue.yaml
  - application-green.yaml
  - service.yaml
  - istio.yaml

namespace: science